In [1]:
import pandas as pd
import numpy as np
from scipy.stats.stats import pearsonr  
from pandas.tseries.holiday import USFederalHolidayCalendar
from pandas.tseries.offsets import CustomBusinessDay
from datetime import datetime
from sklearn.model_selection import train_test_split
import math
import matplotlib.pyplot as plt
from sklearn.feature_selection import SelectKBest
from sklearn.pipeline import Pipeline
from sklearn.decomposition import PCA
from sklearn.grid_search import GridSearchCV
from sklearn.pipeline import FeatureUnion
from sklearn.ensemble import RandomForestRegressor, GradientBoostingRegressor, AdaBoostRegressor
from sklearn.tree import DecisionTreeRegressor
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import cross_val_score
from sklearn.cross_validation import KFold
from sklearn.metrics import mean_squared_error, median_absolute_error
import xgboost as xgb

/Users/fredlu/anaconda/lib/python2.7/site-packages/sklearn/cross_validation.py:44: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)
/Users/fredlu/anaconda/lib/python2.7/site-packages/sklearn/grid_search.py:43: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. This module will be removed in 0.20.
  DeprecationWarning)

In [2]:
df = pd.read_csv("dataclean/trip.csv")
weather = pd.read_csv("dataclean/weather.csv")
stations = pd.read_csv("dataclean/station.csv")
df.head()

,id,duration,start_date,start_station_name,start_station_id,end_date,end_station_name,end_station_id,bike_id,subscription_type,zip_code
0,4576,63,8/29/2013 14:13,South Van Ness at Market,66,8/29/2013 14:14,South Van Ness at Market,66,520,Subscriber,94127
1,4607,70,8/29/2013 14:42,San Jose City Hall,10,8/29/2013 14:43,San Jose City Hall,10,661,Subscriber,95138
2,4130,71,8/29/2013 10:16,Mountain View City Hall,27,8/29/2013 10:17,Mountain View City Hall,27,48,Subscriber,97214
3,4251,77,8/29/2013 11:29,San Jose City Hall,10,8/29/2013 11:30,San Jose City Hall,10,26,Subscriber,95060
4,4299,83,8/29/2013 12:02,South Van Ness at Market,66,8/29/2013 12:04,Market at 10th,67,319,Subscriber,94103

In [3]:
df.duration.describe()

count    6.699590e+05
mean     1.107950e+03
std      2.225544e+04
min      6.000000e+01
25%      3.440000e+02
50%      5.170000e+02
75%      7.550000e+02
max      1.727040e+07
Name: duration, dtype: float64

In [4]:
#Change duration from seconds to minutes
df.duration /= 60
df.duration.describe()

count    669959.000000
mean         18.465831
std         370.923950
min           1.000000
25%           5.733333
50%           8.616667
75%          12.583333
max      287840.000000
Name: duration, dtype: float64

In [5]:
df['duration'].quantile(0.995)
df = df[df.duration <= 360]
df.shape

(666872, 11)

In [6]:
df.start_date = pd.to_datetime(df.start_date, format='%m/%d/%Y %H:%M')

In [7]:
df.head()

,id,duration,start_date,start_station_name,start_station_id,end_date,end_station_name,end_station_id,bike_id,subscription_type,zip_code
0,4576,1.050000,2013-08-29 14:13:00,South Van Ness at Market,66,8/29/2013 14:14,South Van Ness at Market,66,520,Subscriber,94127
1,4607,1.166667,2013-08-29 14:42:00,San Jose City Hall,10,8/29/2013 14:43,San Jose City Hall,10,661,Subscriber,95138
2,4130,1.183333,2013-08-29 10:16:00,Mountain View City Hall,27,8/29/2013 10:17,Mountain View City Hall,27,48,Subscriber,97214
3,4251,1.283333,2013-08-29 11:29:00,San Jose City Hall,10,8/29/2013 11:30,San Jose City Hall,10,26,Subscriber,95060
4,4299,1.383333,2013-08-29 12:02:00,South Van Ness at Market,66,8/29/2013 12:04,Market at 10th,67,319,Subscriber,94103

In [8]:
df['date'] = df.start_date.dt.date
df.head()

,id,duration,start_date,start_station_name,start_station_id,end_date,end_station_name,end_station_id,bike_id,subscription_type,zip_code,date
0,4576,1.050000,2013-08-29 14:13:00,South Van Ness at Market,66,8/29/2013 14:14,South Van Ness at Market,66,520,Subscriber,94127,2013-08-29
1,4607,1.166667,2013-08-29 14:42:00,San Jose City Hall,10,8/29/2013 14:43,San Jose City Hall,10,661,Subscriber,95138,2013-08-29
2,4130,1.183333,2013-08-29 10:16:00,Mountain View City Hall,27,8/29/2013 10:17,Mountain View City Hall,27,48,Subscriber,97214,2013-08-29
3,4251,1.283333,2013-08-29 11:29:00,San Jose City Hall,10,8/29/2013 11:30,San Jose City Hall,10,26,Subscriber,95060,2013-08-29
4,4299,1.383333,2013-08-29 12:02:00,South Van Ness at Market,66,8/29/2013 12:04,Market at 10th,67,319,Subscriber,94103,2013-08-29

In [9]:
dates = {}
for d in df.date:
    if d not in dates:
        dates[d] = 1
    else:
        dates[d] += 1

In [10]:
dates

{datetime.date(2013, 8, 29): 742,
 datetime.date(2013, 8, 30): 699,
 datetime.date(2013, 8, 31): 628,
 datetime.date(2013, 9, 1): 683,
 datetime.date(2013, 9, 2): 652,
 datetime.date(2013, 9, 3): 592,
 datetime.date(2013, 9, 4): 599,
 datetime.date(2013, 9, 5): 671,
 datetime.date(2013, 9, 6): 810,
 datetime.date(2013, 9, 7): 788,
 datetime.date(2013, 9, 8): 692,
 datetime.date(2013, 9, 9): 765,
 datetime.date(2013, 9, 10): 892,
 datetime.date(2013, 9, 11): 876,
 datetime.date(2013, 9, 12): 933,
 datetime.date(2013, 9, 13): 969,
 datetime.date(2013, 9, 14): 690,
 datetime.date(2013, 9, 15): 613,
 datetime.date(2013, 9, 16): 912,
 datetime.date(2013, 9, 17): 1066,
 datetime.date(2013, 9, 18): 1106,
 datetime.date(2013, 9, 19): 1044,
 datetime.date(2013, 9, 20): 1101,
 datetime.date(2013, 9, 21): 384,
 datetime.date(2013, 9, 22): 567,
 datetime.date(2013, 9, 23): 1044,
 datetime.date(2013, 9, 24): 1070,
 datetime.date(2013, 9, 25): 1260,
 datetime.date(2013, 9, 26): 1079,
 datetime.date(2013, 9, 27): 1095,
 datetime.date(2013, 9, 28): 606,
 datetime.date(2013, 9, 29): 513,
 datetime.date(2013, 9, 30): 969,
 datetime.date(2013, 10, 1): 1063,
 datetime.date(2013, 10, 2): 1058,
 datetime.date(2013, 10, 3): 1150,
 datetime.date(2013, 10, 4): 1085,
 datetime.date(2013, 10, 5): 709,
 datetime.date(2013, 10, 6): 597,
 datetime.date(2013, 10, 7): 961,
 datetime.date(2013, 10, 8): 1009,
 datetime.date(2013, 10, 9): 1064,
 datetime.date(2013, 10, 10): 1085,
 datetime.date(2013, 10, 11): 1011,
 datetime.date(2013, 10, 12): 659,
 datetime.date(2013, 10, 13): 562,
 datetime.date(2013, 10, 14): 1040,
 datetime.date(2013, 10, 15): 1166,
 datetime.date(2013, 10, 16): 1159,
 datetime.date(2013, 10, 17): 1224,
 datetime.date(2013, 10, 18): 1097,
 datetime.date(2013, 10, 19): 625,
 datetime.date(2013, 10, 20): 444,
 datetime.date(2013, 10, 21): 1014,
 datetime.date(2013, 10, 22): 1026,
 datetime.date(2013, 10, 23): 1026,
 datetime.date(2013, 10, 24): 1051,
 datetime.date(2013, 10, 25): 1041,
 datetime.date(2013, 10, 26): 487,
 datetime.date(2013, 10, 27): 287,
 datetime.date(2013, 10, 28): 965,
 datetime.date(2013, 10, 29): 1007,
 datetime.date(2013, 10, 30): 1121,
 datetime.date(2013, 10, 31): 1148,
 datetime.date(2013, 11, 1): 1118,
 datetime.date(2013, 11, 2): 538,
 datetime.date(2013, 11, 3): 371,
 datetime.date(2013, 11, 4): 1122,
 datetime.date(2013, 11, 5): 1156,
 datetime.date(2013, 11, 6): 1083,
 datetime.date(2013, 11, 7): 1193,
 datetime.date(2013, 11, 8): 1166,
 datetime.date(2013, 11, 9): 622,
 datetime.date(2013, 11, 10): 479,
 datetime.date(2013, 11, 11): 982,
 datetime.date(2013, 11, 12): 1151,
 datetime.date(2013, 11, 13): 1001,
 datetime.date(2013, 11, 14): 1112,
 datetime.date(2013, 11, 15): 1124,
 datetime.date(2013, 11, 16): 466,
 datetime.date(2013, 11, 17): 404,
 datetime.date(2013, 11, 18): 1005,
 datetime.date(2013, 11, 19): 750,
 datetime.date(2013, 11, 20): 622,
 datetime.date(2013, 11, 21): 1101,
 datetime.date(2013, 11, 22): 993,
 datetime.date(2013, 11, 23): 522,
 datetime.date(2013, 11, 24): 343,
 datetime.date(2013, 11, 25): 1018,
 datetime.date(2013, 11, 26): 1002,
 datetime.date(2013, 11, 27): 717,
 datetime.date(2013, 11, 28): 266,
 datetime.date(2013, 11, 29): 369,
 datetime.date(2013, 11, 30): 303,
 datetime.date(2013, 12, 1): 324,
 datetime.date(2013, 12, 2): 877,
 datetime.date(2013, 12, 3): 915,
 datetime.date(2013, 12, 4): 990,
 datetime.date(2013, 12, 5): 933,
 datetime.date(2013, 12, 6): 725,
 datetime.date(2013, 12, 7): 277,
 datetime.date(2013, 12, 8): 274,
 datetime.date(2013, 12, 9): 806,
 datetime.date(2013, 12, 10): 877,
 datetime.date(2013, 12, 11): 901,
 datetime.date(2013, 12, 12): 963,
 datetime.date(2013, 12, 13): 961,
 datetime.date(2013, 12, 14): 387,
 datetime.date(2013, 12, 15): 311,
 datetime.date(2013, 12, 16): 940,
 datetime.date(2013, 12, 17): 975,
 datetime.date(2013, 12, 18): 925,
 datetime.date(2013, 12, 19): 935,
 datetime.date(2013, 12, 20): 866,
 datetime.date(2013, 12, 21): 350,
 datetime.date(2013, 12, 22): 292,
 datetime.date(2013, 12, 23): 644,
 datetime.date(2013, 12, 24): 330,
 datetime.date(2013, 12, 25): 355,
 datetime.date(2013, 12, 26): 419,
 datetime.date(2013, 12, 27): 422,
 datetime.date(2013, 12, 28): 395,
 datetime.date(2013, 12, 29): 311,
 datetime.date(2013, 12, 30): 603,
 datetime.date(2013, 12, 31): 499,
 datetime.date(2014, 1, 1): 352,
 datetime.date(2014, 1, 2): 765,
 datetime.date(2014, 1, 3): 771,
 datetime.date(2014, 1, 4): 353,
 datetime.date(2014, 1, 5): 294,
 datetime.date(2014, 1, 6): 910,
 datetime.date(2014, 1, 7): 966,
 datetime.date(2014, 1, 8): 963,
 datetime.date(2014, 1, 9): 977,
 datetime.date(2014, 1, 10): 982,
 datetime.date(2014, 1, 11): 243,
 datetime.date(2014, 1, 12): 348,
 datetime.date(2014, 1, 13): 1011,
 datetime.date(2014, 1, 14): 1026,
 datetime.date(2014, 1, 15): 1098,
 datetime.date(2014, 1, 16): 1095,
 datetime.date(2014, 1, 17): 1012,
 datetime.date(2014, 1, 18): 435,
 datetime.date(2014, 1, 19): 393,
 datetime.date(2014, 1, 20): 611,
 datetime.date(2014, 1, 21): 1008,
 datetime.date(2014, 1, 22): 1069,
 datetime.date(2014, 1, 23): 1093,
 datetime.date(2014, 1, 24): 1019,
 datetime.date(2014, 1, 25): 438,
 datetime.date(2014, 1, 26): 390,
 datetime.date(2014, 1, 27): 959,
 datetime.date(2014, 1, 28): 1019,
 datetime.date(2014, 1, 29): 952,
 datetime.date(2014, 1, 30): 943,
 datetime.date(2014, 1, 31): 836,
 datetime.date(2014, 2, 1): 379,
 datetime.date(2014, 2, 2): 127,
 datetime.date(2014, 2, 3): 960,
 datetime.date(2014, 2, 4): 986,
 datetime.date(2014, 2, 5): 858,
 datetime.date(2014, 2, 6): 483,
 datetime.date(2014, 2, 7): 466,
 datetime.date(2014, 2, 8): 92,
 datetime.date(2014, 2, 9): 81,
 datetime.date(2014, 2, 10): 801,
 datetime.date(2014, 2, 11): 938,
 datetime.date(2014, 2, 12): 1010,
 datetime.date(2014, 2, 13): 935,
 datetime.date(2014, 2, 14): 951,
 datetime.date(2014, 2, 15): 413,
 datetime.date(2014, 2, 16): 413,
 datetime.date(2014, 2, 17): 462,
 datetime.date(2014, 2, 18): 1009,
 datetime.date(2014, 2, 19): 1007,
 datetime.date(2014, 2, 20): 969,
 datetime.date(2014, 2, 21): 935,
 datetime.date(2014, 2, 22): 459,
 datetime.date(2014, 2, 23): 312,
 datetime.date(2014, 2, 24): 1004,
 datetime.date(2014, 2, 25): 1083,
 datetime.date(2014, 2, 26): 392,
 datetime.date(2014, 2, 27): 867,
 datetime.date(2014, 2, 28): 534,
 datetime.date(2014, 3, 1): 311,
 datetime.date(2014, 3, 2): 206,
 datetime.date(2014, 3, 3): 744,
 datetime.date(2014, 3, 4): 943,
 datetime.date(2014, 3, 5): 976,
 datetime.date(2014, 3, 6): 1012,
 datetime.date(2014, 3, 7): 982,
 datetime.date(2014, 3, 8): 460,
 datetime.date(2014, 3, 9): 544,
 datetime.date(2014, 3, 10): 978,
 datetime.date(2014, 3, 11): 1108,
 datetime.date(2014, 3, 12): 1040,
 datetime.date(2014, 3, 13): 1132,
 datetime.date(2014, 3, 14): 1022,
 datetime.date(2014, 3, 15): 488,
 datetime.date(2014, 3, 16): 436,
 datetime.date(2014, 3, 17): 998,
 datetime.date(2014, 3, 18): 1138,
 datetime.date(2014, 3, 19): 1160,
 datetime.date(2014, 3, 20): 1126,
 datetime.date(2014, 3, 21): 1000,
 datetime.date(2014, 3, 22): 413,
 datetime.date(2014, 3, 23): 366,
 datetime.date(2014, 3, 24): 1011,
 datetime.date(2014, 3, 25): 926,
 datetime.date(2014, 3, 26): 716,
 datetime.date(2014, 3, 27): 1069,
 datetime.date(2014, 3, 28): 972,
 datetime.date(2014, 3, 29): 113,
 datetime.date(2014, 3, 30): 388,
 datetime.date(2014, 3, 31): 695,
 datetime.date(2014, 4, 1): 520,
 datetime.date(2014, 4, 2): 985,
 datetime.date(2014, 4, 3): 995,
 datetime.date(2014, 4, 4): 842,
 datetime.date(2014, 4, 5): 506,
 datetime.date(2014, 4, 6): 366,
 datetime.date(2014, 4, 7): 1122,
 datetime.date(2014, 4, 8): 1268,
 datetime.date(2014, 4, 9): 1118,
 datetime.date(2014, 4, 10): 1027,
 datetime.date(2014, 4, 11): 1008,
 datetime.date(2014, 4, 12): 460,
 datetime.date(2014, 4, 13): 408,
 datetime.date(2014, 4, 14): 1044,
 datetime.date(2014, 4, 15): 1161,
 datetime.date(2014, 4, 16): 1221,
 datetime.date(2014, 4, 17): 1141,
 datetime.date(2014, 4, 18): 978,
 datetime.date(2014, 4, 19): 414,
 datetime.date(2014, 4, 20): 358,
 datetime.date(2014, 4, 21): 1048,
 datetime.date(2014, 4, 22): 1064,
 datetime.date(2014, 4, 23): 1083,
 datetime.date(2014, 4, 24): 1016,
 datetime.date(2014, 4, 25): 598,
 datetime.date(2014, 4, 26): 377,
 datetime.date(2014, 4, 27): 350,
 datetime.date(2014, 4, 28): 1174,
 datetime.date(2014, 4, 29): 1225,
 datetime.date(2014, 4, 30): 1222,
 datetime.date(2014, 5, 1): 1180,
 datetime.date(2014, 5, 2): 1033,
 datetime.date(2014, 5, 3): 385,
 datetime.date(2014, 5, 4): 411,
 datetime.date(2014, 5, 5): 1153,
 datetime.date(2014, 5, 6): 1124,
 datetime.date(2014, 5, 7): 1172,
 datetime.date(2014, 5, 8): 1051,
 datetime.date(2014, 5, 9): 1036,
 datetime.date(2014, 5, 10): 433,
 datetime.date(2014, 5, 11): 330,
 datetime.date(2014, 5, 12): 1178,
 datetime.date(2014, 5, 13): 1232,
 datetime.date(2014, 5, 14): 1176,
 datetime.date(2014, 5, 15): 1204,
 datetime.date(2014, 5, 16): 1130,
 datetime.date(2014, 5, 17): 466,
 datetime.date(2014, 5, 18): 411,
 datetime.date(2014, 5, 19): 1111,
 datetime.date(2014, 5, 20): 1123,
 datetime.date(2014, 5, 21): 1100,
 datetime.date(2014, 5, 22): 1213,
 datetime.date(2014, 5, 23): 1092,
 datetime.date(2014, 5, 24): 426,
 datetime.date(2014, 5, 25): 538,
 datetime.date(2014, 5, 26): 445,
 datetime.date(2014, 5, 27): 1200,
 datetime.date(2014, 5, 28): 1270,
 datetime.date(2014, 5, 29): 1207,
 datetime.date(2014, 5, 30): 1071,
 datetime.date(2014, 5, 31): 437,
 datetime.date(2014, 6, 1): 459,
 datetime.date(2014, 6, 2): 1283,
 datetime.date(2014, 6, 3): 1315,
 datetime.date(2014, 6, 4): 1290,
 datetime.date(2014, 6, 5): 1214,
 datetime.date(2014, 6, 6): 1155,
 datetime.date(2014, 6, 7): 430,
 datetime.date(2014, 6, 8): 493,
 datetime.date(2014, 6, 9): 1292,
 datetime.date(2014, 6, 10): 1252,
 datetime.date(2014, 6, 11): 1276,
 datetime.date(2014, 6, 12): 1171,
 datetime.date(2014, 6, 13): 1158,
 datetime.date(2014, 6, 14): 430,
 datetime.date(2014, 6, 15): 389,
 datetime.date(2014, 6, 16): 1265,
 datetime.date(2014, 6, 17): 1214,
 datetime.date(2014, 6, 18): 1251,
 datetime.date(2014, 6, 19): 1234,
 datetime.date(2014, 6, 20): 1149,
 datetime.date(2014, 6, 21): 356,
 datetime.date(2014, 6, 22): 452,
 datetime.date(2014, 6, 23): 1184,
 datetime.date(2014, 6, 24): 1330,
 datetime.date(2014, 6, 25): 1221,
 datetime.date(2014, 6, 26): 1286,
 datetime.date(2014, 6, 27): 1130,
 datetime.date(2014, 6, 28): 481,
 datetime.date(2014, 6, 29): 407,
 datetime.date(2014, 6, 30): 1244,
 datetime.date(2014, 7, 1): 1203,
 datetime.date(2014, 7, 2): 1241,
 datetime.date(2014, 7, 3): 1019,
 datetime.date(2014, 7, 4): 377,
 datetime.date(2014, 7, 5): 373,
 datetime.date(2014, 7, 6): 363,
 datetime.date(2014, 7, 7): 1208,
 datetime.date(2014, 7, 8): 1198,
 datetime.date(2014, 7, 9): 1340,
 datetime.date(2014, 7, 10): 1223,
 datetime.date(2014, 7, 11): 1072,
 datetime.date(2014, 7, 12): 433,
 datetime.date(2014, 7, 13): 403,
 datetime.date(2014, 7, 14): 1218,
 datetime.date(2014, 7, 15): 1296,
 datetime.date(2014, 7, 16): 1309,
 datetime.date(2014, 7, 17): 1298,
 datetime.date(2014, 7, 18): 1154,
 datetime.date(2014, 7, 19): 417,
 datetime.date(2014, 7, 20): 392,
 datetime.date(2014, 7, 21): 1222,
 datetime.date(2014, 7, 22): 1325,
 datetime.date(2014, 7, 23): 1363,
 datetime.date(2014, 7, 24): 1296,
 datetime.date(2014, 7, 25): 1197,
 datetime.date(2014, 7, 26): 485,
 datetime.date(2014, 7, 27): 436,
 datetime.date(2014, 7, 28): 1291,
 datetime.date(2014, 7, 29): 1363,
 datetime.date(2014, 7, 30): 1343,
 datetime.date(2014, 7, 31): 1253,
 datetime.date(2014, 8, 1): 1159,
 datetime.date(2014, 8, 2): 386,
 datetime.date(2014, 8, 3): 361,
 datetime.date(2014, 8, 4): 1164,
 datetime.date(2014, 8, 5): 1308,
 datetime.date(2014, 8, 6): 1254,
 datetime.date(2014, 8, 7): 1250,
 datetime.date(2014, 8, 8): 1164,
 datetime.date(2014, 8, 9): 373,
 datetime.date(2014, 8, 10): 428,
 datetime.date(2014, 8, 11): 1231,
 datetime.date(2014, 8, 12): 1377,
 datetime.date(2014, 8, 13): 1247,
 datetime.date(2014, 8, 14): 1246,
 datetime.date(2014, 8, 15): 1177,
 datetime.date(2014, 8, 16): 415,
 datetime.date(2014, 8, 17): 396,
 datetime.date(2014, 8, 18): 1271,
 datetime.date(2014, 8, 19): 1274,
 datetime.date(2014, 8, 20): 1323,
 datetime.date(2014, 8, 21): 1345,
 datetime.date(2014, 8, 22): 1227,
 datetime.date(2014, 8, 23): 473,
 datetime.date(2014, 8, 24): 335,
 datetime.date(2014, 8, 25): 1369,
 datetime.date(2014, 8, 26): 1509,
 datetime.date(2014, 8, 27): 1472,
 datetime.date(2014, 8, 28): 1338,
 datetime.date(2014, 8, 29): 1243,
 datetime.date(2014, 8, 30): 469,
 datetime.date(2014, 8, 31): 464,
 datetime.date(2014, 9, 1): 362,
 datetime.date(2014, 9, 2): 1315,
 datetime.date(2014, 9, 3): 1403,
 datetime.date(2014, 9, 4): 1386,
 datetime.date(2014, 9, 5): 1259,
 datetime.date(2014, 9, 6): 433,
 datetime.date(2014, 9, 7): 328,
 datetime.date(2014, 9, 8): 1301,
 datetime.date(2014, 9, 9): 1352,
 datetime.date(2014, 9, 10): 1344,
 datetime.date(2014, 9, 11): 1378,
 datetime.date(2014, 9, 12): 1300,
 datetime.date(2014, 9, 13): 551,
 datetime.date(2014, 9, 14): 429,
 datetime.date(2014, 9, 15): 1505,
 datetime.date(2014, 9, 16): 1428,
 datetime.date(2014, 9, 17): 1425,
 datetime.date(2014, 9, 18): 1184,
 datetime.date(2014, 9, 19): 1243,
 datetime.date(2014, 9, 20): 424,
 datetime.date(2014, 9, 21): 308,
 datetime.date(2014, 9, 22): 1349,
 datetime.date(2014, 9, 23): 1361,
 datetime.date(2014, 9, 24): 1294,
 datetime.date(2014, 9, 25): 1173,
 datetime.date(2014, 9, 26): 1237,
 datetime.date(2014, 9, 27): 462,
 datetime.date(2014, 9, 28): 368,
 datetime.date(2014, 9, 29): 1333,
 datetime.date(2014, 9, 30): 1304,
 datetime.date(2014, 10, 1): 1390,
 datetime.date(2014, 10, 2): 1448,
 datetime.date(2014, 10, 3): 1192,
 datetime.date(2014, 10, 4): 412,
 datetime.date(2014, 10, 5): 320,
 datetime.date(2014, 10, 6): 1168,
 datetime.date(2014, 10, 7): 1289,
 datetime.date(2014, 10, 8): 1366,
 datetime.date(2014, 10, 9): 1305,
 datetime.date(2014, 10, 10): 1290,
 datetime.date(2014, 10, 11): 545,
 datetime.date(2014, 10, 12): 438,
 datetime.date(2014, 10, 13): 1260,
 datetime.date(2014, 10, 14): 1495,
 datetime.date(2014, 10, 15): 1378,
 datetime.date(2014, 10, 16): 1458,
 datetime.date(2014, 10, 17): 1255,
 datetime.date(2014, 10, 18): 469,
 datetime.date(2014, 10, 19): 414,
 datetime.date(2014, 10, 20): 1263,
 datetime.date(2014, 10, 21): 1409,
 datetime.date(2014, 10, 22): 1317,
 datetime.date(2014, 10, 23): 1387,
 datetime.date(2014, 10, 24): 1424,
 datetime.date(2014, 10, 25): 403,
 datetime.date(2014, 10, 26): 467,
 datetime.date(2014, 10, 27): 1392,
 datetime.date(2014, 10, 28): 1418,
 datetime.date(2014, 10, 29): 1494,
 datetime.date(2014, 10, 30): 1405,
 datetime.date(2014, 10, 31): 845,
 datetime.date(2014, 11, 1): 392,
 datetime.date(2014, 11, 2): 368,
 datetime.date(2014, 11, 3): 1344,
 datetime.date(2014, 11, 4): 1299,
 datetime.date(2014, 11, 5): 1377,
 datetime.date(2014, 11, 6): 1410,
 datetime.date(2014, 11, 7): 1300,
 datetime.date(2014, 11, 8): 506,
 datetime.date(2014, 11, 9): 372,
 datetime.date(2014, 11, 10): 1304,
 datetime.date(2014, 11, 11): 1212,
 datetime.date(2014, 11, 12): 1361,
 datetime.date(2014, 11, 13): 1133,
 datetime.date(2014, 11, 14): 1210,
 datetime.date(2014, 11, 15): 377,
 datetime.date(2014, 11, 16): 266,
 datetime.date(2014, 11, 17): 1303,
 datetime.date(2014, 11, 18): 1322,
 datetime.date(2014, 11, 19): 905,
 datetime.date(2014, 11, 20): 885,
 datetime.date(2014, 11, 21): 1210,
 datetime.date(2014, 11, 22): 338,
 datetime.date(2014, 11, 23): 235,
 datetime.date(2014, 11, 24): 1283,
 datetime.date(2014, 11, 25): 1177,
 datetime.date(2014, 11, 26): 757,
 datetime.date(2014, 11, 27): 130,
 datetime.date(2014, 11, 28): 275,
 datetime.date(2014, 11, 29): 280,
 datetime.date(2014, 11, 30): 121,
 datetime.date(2014, 12, 1): 1180,
 datetime.date(2014, 12, 2): 491,
 datetime.date(2014, 12, 3): 804,
 datetime.date(2014, 12, 4): 1121,
 datetime.date(2014, 12, 5): 979,
 datetime.date(2014, 12, 6): 415,
 datetime.date(2014, 12, 7): 291,
 datetime.date(2014, 12, 8): 1359,
 datetime.date(2014, 12, 9): 1304,
 datetime.date(2014, 12, 10): 1277,
 datetime.date(2014, 12, 11): 105,
 datetime.date(2014, 12, 12): 591,
 datetime.date(2014, 12, 13): 361,
 datetime.date(2014, 12, 14): 254,
 datetime.date(2014, 12, 15): 618,
 datetime.date(2014, 12, 16): 736,
 datetime.date(2014, 12, 17): 783,
 datetime.date(2014, 12, 18): 1124,
 datetime.date(2014, 12, 19): 530,
 datetime.date(2014, 12, 20): 302,
 datetime.date(2014, 12, 21): 244,
 datetime.date(2014, 12, 22): 1014,
 datetime.date(2014, 12, 23): 802,
 datetime.date(2014, 12, 24): 308,
 datetime.date(2014, 12, 25): 150,
 datetime.date(2014, 12, 26): 321,
 datetime.date(2014, 12, 27): 227,
 datetime.date(2014, 12, 28): 296,
 datetime.date(2014, 12, 29): 624,
 datetime.date(2014, 12, 30): 481,
 datetime.date(2014, 12, 31): 381,
 datetime.date(2015, 1, 1): 179,
 datetime.date(2015, 1, 2): 424,
 datetime.date(2015, 1, 3): 279,
 datetime.date(2015, 1, 4): 202,
 datetime.date(2015, 1, 5): 1185,
 datetime.date(2015, 1, 6): 1255,
 datetime.date(2015, 1, 7): 1299,
 datetime.date(2015, 1, 8): 1292,
 datetime.date(2015, 1, 9): 1173,
 datetime.date(2015, 1, 10): 355,
 datetime.date(2015, 1, 11): 326,
 datetime.date(2015, 1, 12): 1344,
 datetime.date(2015, 1, 13): 1364,
 datetime.date(2015, 1, 14): 1295,
 datetime.date(2015, 1, 15): 1227,
 datetime.date(2015, 1, 16): 1077,
 datetime.date(2015, 1, 17): 315,
 datetime.date(2015, 1, 18): 269,
 datetime.date(2015, 1, 19): 619,
 datetime.date(2015, 1, 20): 1213,
 datetime.date(2015, 1, 21): 1311,
 datetime.date(2015, 1, 22): 1222,
 datetime.date(2015, 1, 23): 1164,
 datetime.date(2015, 1, 24): 418,
 datetime.date(2015, 1, 25): 254,
 datetime.date(2015, 1, 26): 1245,
 datetime.date(2015, 1, 27): 1259,
 datetime.date(2015, 1, 28): 1340,
 datetime.date(2015, 1, 29): 1290,
 datetime.date(2015, 1, 30): 1190,
 datetime.date(2015, 1, 31): 368,
 datetime.date(2015, 2, 1): 250,
 datetime.date(2015, 2, 2): 1309,
 datetime.date(2015, 2, 3): 1360,
 datetime.date(2015, 2, 4): 1364,
 datetime.date(2015, 2, 5): 1272,
 datetime.date(2015, 2, 6): 608,
 datetime.date(2015, 2, 7): 315,
 datetime.date(2015, 2, 8): 136,
 datetime.date(2015, 2, 9): 1244,
 datetime.date(2015, 2, 10): 1367,
 datetime.date(2015, 2, 11): 1343,
 datetime.date(2015, 2, 12): 1304,
 datetime.date(2015, 2, 13): 1290,
 datetime.date(2015, 2, 14): 557,
 datetime.date(2015, 2, 15): 366,
 datetime.date(2015, 2, 16): 543,
 datetime.date(2015, 2, 17): 1278,
 datetime.date(2015, 2, 18): 1235,
 datetime.date(2015, 2, 19): 1171,
 datetime.date(2015, 2, 20): 1097,
 datetime.date(2015, 2, 21): 332,
 datetime.date(2015, 2, 22): 283,
 datetime.date(2015, 2, 23): 1277,
 datetime.date(2015, 2, 24): 1167,
 datetime.date(2015, 2, 25): 1208,
 datetime.date(2015, 2, 26): 1240,
 datetime.date(2015, 2, 27): 1086,
 datetime.date(2015, 2, 28): 329,
 datetime.date(2015, 3, 1): 333,
 datetime.date(2015, 3, 2): 1209,
 datetime.date(2015, 3, 3): 1296,
 datetime.date(2015, 3, 4): 1242,
 datetime.date(2015, 3, 5): 1222,
 datetime.date(2015, 3, 6): 1240,
 datetime.date(2015, 3, 7): 386,
 datetime.date(2015, 3, 8): 392,
 datetime.date(2015, 3, 9): 1042,
 datetime.date(2015, 3, 10): 1183,
 datetime.date(2015, 3, 11): 1211,
 datetime.date(2015, 3, 12): 1325,
 datetime.date(2015, 3, 13): 1207,
 datetime.date(2015, 3, 14): 469,
 datetime.date(2015, 3, 15): 372,
 datetime.date(2015, 3, 16): 1295,
 datetime.date(2015, 3, 17): 1362,
 datetime.date(2015, 3, 18): 1317,
 datetime.date(2015, 3, 19): 1361,
 datetime.date(2015, 3, 20): 1203,
 datetime.date(2015, 3, 21): 373,
 datetime.date(2015, 3, 22): 278,
 datetime.date(2015, 3, 23): 1243,
 datetime.date(2015, 3, 24): 1337,
 datetime.date(2015, 3, 25): 1404,
 datetime.date(2015, 3, 26): 1346,
 datetime.date(2015, 3, 27): 1264,
 datetime.date(2015, 3, 28): 505,
 datetime.date(2015, 3, 29): 360,
 datetime.date(2015, 3, 30): 1403,

In [11]:
train = pd.DataFrame(dates.items(), columns=['date', 'trips'])
train

           date  trips
0    2015-07-26    432
1    2013-10-18   1097
2    2014-06-16   1265
3    2014-11-24   1283
4    2015-04-02   1389
5    2013-11-30    303
6    2015-03-26   1346
7    2014-05-12   1178
8    2014-04-12    460
9    2013-09-05    671
10   2013-12-11    901
11   2015-06-02   1384
12   2015-05-26   1219
13   2015-01-05   1185
14   2014-07-01   1203
15   2015-02-18   1235
16   2015-07-17   1246
17   2013-10-27    287
18   2015-08-02    317
19   2014-06-27   1130
20   2014-12-06    415
21   2014-11-17   1303
22   2015-04-27   1231
23   2013-11-17    404
24   2015-03-01    333
25   2014-05-05   1153
26   2014-04-11   1008
27   2013-09-12    933
28   2014-09-29   1333
29   2013-12-04    990
..          ...    ...
703  2014-02-25   1083
704  2015-08-29    341
705  2015-01-24    418
706  2014-12-31    381
707  2014-01-19    393
708  2015-07-12    370
709  2015-04-12    302
710  2015-03-20   1203
711  2014-10-23   1387
712  2014-09-04   1386
713  2014-03-24   1011
714  2013-09-23   1044
715  2014-08-04   1164
716  2013-12-25    355
717  2014-02-16    413
718  2015-01-19    619
719  2014-07-19    417
720  2014-01-20    611
721  2015-07-03    430
722  2013-10-21   1014
723  2015-04-05    212
724  2015-03-19   1361
725  2014-10-30   1405
726  2013-09-30    969
727  2013-12-18    925
728  2015-06-09   1380
729  2015-05-19   1379
730  2015-01-10    355
731  2014-07-24   1296
732  2014-01-29    952

[733 rows x 2 columns]

In [12]:
train = train.sort('date')
train.reset_index(drop=True, inplace=True)
train

/Users/fredlu/anaconda/lib/python2.7/site-packages/ipykernel/__main__.py:1: FutureWarning: sort(columns=....) is deprecated, use sort_values(by=.....)
  if __name__ == '__main__':

           date  trips
0    2013-08-29    742
1    2013-08-30    699
2    2013-08-31    628
3    2013-09-01    683
4    2013-09-02    652
5    2013-09-03    592
6    2013-09-04    599
7    2013-09-05    671
8    2013-09-06    810
9    2013-09-07    788
10   2013-09-08    692
11   2013-09-09    765
12   2013-09-10    892
13   2013-09-11    876
14   2013-09-12    933
15   2013-09-13    969
16   2013-09-14    690
17   2013-09-15    613
18   2013-09-16    912
19   2013-09-17   1066
20   2013-09-18   1106
21   2013-09-19   1044
22   2013-09-20   1101
23   2013-09-21    384
24   2013-09-22    567
25   2013-09-23   1044
26   2013-09-24   1070
27   2013-09-25   1260
28   2013-09-26   1079
29   2013-09-27   1095
..          ...    ...
703  2015-08-02    317
704  2015-08-03   1278
705  2015-08-04   1356
706  2015-08-05   1334
707  2015-08-06   1296
708  2015-08-07   1192
709  2015-08-08    427
710  2015-08-09    357
711  2015-08-10   1280
712  2015-08-11   1395
713  2015-08-12   1396
714  2015-08-13   1399
715  2015-08-14   1178
716  2015-08-15    445
717  2015-08-16    392
718  2015-08-17   1418
719  2015-08-18   1405
720  2015-08-19   1345
721  2015-08-20   1351
722  2015-08-21   1211
723  2015-08-22    417
724  2015-08-23    308
725  2015-08-24   1300
726  2015-08-25   1418
727  2015-08-26   1464
728  2015-08-27   1439
729  2015-08-28   1219
730  2015-08-29    341
731  2015-08-30    326
732  2015-08-31   1367

[733 rows x 2 columns]

In [13]:
weather.head()

,date,max_temperature_f,mean_temperature_f,min_temperature_f,max_dew_point_f,mean_dew_point_f,min_dew_point_f,max_humidity,mean_humidity,min_humidity,...,mean_visibility_miles,min_visibility_miles,max_wind_Speed_mph,mean_wind_speed_mph,max_gust_speed_mph,precipitation_inches,cloud_cover,events,wind_dir_degrees,zip_code
0,8/29/2013,74.0,68.0,61.0,61.0,58.0,56.0,93.0,75.0,57.0,...,10.0,10.0,23.0,11.0,28.0,0,4.0,NaN,286.0,94107
1,8/30/2013,78.0,69.0,60.0,61.0,58.0,56.0,90.0,70.0,50.0,...,10.0,7.0,29.0,13.0,35.0,0,2.0,NaN,291.0,94107
2,8/31/2013,71.0,64.0,57.0,57.0,56.0,54.0,93.0,75.0,57.0,...,10.0,10.0,26.0,15.0,31.0,0,4.0,NaN,284.0,94107
3,9/1/2013,74.0,66.0,58.0,60.0,56.0,53.0,87.0,68.0,49.0,...,10.0,10.0,25.0,13.0,29.0,0,4.0,NaN,284.0,94107
4,9/2/2013,75.0,69.0,62.0,61.0,60.0,58.0,93.0,77.0,61.0,...,10.0,6.0,23.0,12.0,30.0,0,6.0,NaN,277.0,94107

In [14]:
weather.date = pd.to_datetime(weather.date, format='%m/%d/%Y')

In [16]:
weather.shape

(3665, 24)

In [17]:
weather.zip_code.unique()

array([94107, 94063, 94301, 94041, 95113])

In [19]:
weather = weather[weather.zip_code == 94107]

In [20]:
weather

,date,max_temperature_f,mean_temperature_f,min_temperature_f,max_dew_point_f,mean_dew_point_f,min_dew_point_f,max_humidity,mean_humidity,min_humidity,...,mean_visibility_miles,min_visibility_miles,max_wind_Speed_mph,mean_wind_speed_mph,max_gust_speed_mph,precipitation_inches,cloud_cover,events,wind_dir_degrees,zip_code
0,2013-08-29,74.0,68.0,61.0,61.0,58.0,56.0,93.0,75.0,57.0,...,10.0,10.0,23.0,11.0,28.0,0,4.0,NaN,286.0,94107
1,2013-08-30,78.0,69.0,60.0,61.0,58.0,56.0,90.0,70.0,50.0,...,10.0,7.0,29.0,13.0,35.0,0,2.0,NaN,291.0,94107
2,2013-08-31,71.0,64.0,57.0,57.0,56.0,54.0,93.0,75.0,57.0,...,10.0,10.0,26.0,15.0,31.0,0,4.0,NaN,284.0,94107
3,2013-09-01,74.0,66.0,58.0,60.0,56.0,53.0,87.0,68.0,49.0,...,10.0,10.0,25.0,13.0,29.0,0,4.0,NaN,284.0,94107
4,2013-09-02,75.0,69.0,62.0,61.0,60.0,58.0,93.0,77.0,61.0,...,10.0,6.0,23.0,12.0,30.0,0,6.0,NaN,277.0,94107
5,2013-09-03,73.0,67.0,60.0,59.0,56.0,51.0,84.0,65.0,46.0,...,10.0,10.0,24.0,15.0,31.0,0,2.0,NaN,276.0,94107
6,2013-09-04,74.0,68.0,61.0,59.0,57.0,56.0,90.0,72.0,53.0,...,10.0,10.0,29.0,19.0,35.0,0,4.0,NaN,269.0,94107
7,2013-09-05,72.0,66.0,60.0,57.0,56.0,54.0,90.0,74.0,57.0,...,10.0,10.0,31.0,21.0,37.0,0,3.0,NaN,270.0,94107
8,2013-09-06,85.0,71.0,56.0,57.0,51.0,45.0,86.0,58.0,29.0,...,10.0,10.0,24.0,8.0,28.0,0,0.0,NaN,287.0,94107
9,2013-09-07,88.0,73.0,58.0,64.0,54.0,46.0,86.0,59.0,31.0,...,10.0,10.0,21.0,8.0,25.0,0,1.0,NaN,305.0,94107
10,2013-09-08,74.0,65.0,56.0,58.0,54.0,52.0,86.0,70.0,53.0,...,10.0,10.0,26.0,11.0,31.0,0,2.0,NaN,299.0,94107
11,2013-09-09,76.0,66.0,55.0,58.0,55.0,52.0,90.0,70.0,50.0,...,10.0,10.0,26.0,11.0,30.0,0,1.0,NaN,303.0,94107
12,2013-09-10,74.0,66.0,57.0,59.0,56.0,54.0,93.0,73.0,53.0,...,10.0,10.0,17.0,8.0,21.0,0,1.0,NaN,230.0,94107
13,2013-09-11,74.0,68.0,62.0,57.0,55.0,54.0,78.0,68.0,57.0,...,10.0,10.0,18.0,9.0,23.0,0,5.0,NaN,219.0,94107
14,2013-09-12,71.0,65.0,59.0,58.0,57.0,55.0,84.0,73.0,61.0,...,10.0,9.0,25.0,11.0,30.0,0,7.0,Fog,268.0,94107
15,2013-09-13,66.0,62.0,57.0,55.0,54.0,54.0,93.0,80.0,67.0,...,10.0,7.0,30.0,15.0,37.0,0,6.0,NaN,271.0,94107
16,2013-09-14,66.0,62.0,57.0,55.0,54.0,53.0,87.0,77.0,67.0,...,10.0,9.0,25.0,16.0,33.0,0,7.0,NaN,265.0,94107
17,2013-09-15,73.0,66.0,58.0,59.0,55.0,52.0,90.0,72.0,53.0,...,10.0,6.0,23.0,13.0,26.0,0,5.0,NaN,276.0,94107
18,2013-09-16,71.0,65.0,59.0,58.0,55.0,53.0,90.0,74.0,57.0,...,10.0,6.0,31.0,16.0,39.0,0,3.0,NaN,274.0,94107
19,2013-09-17,68.0,63.0,57.0,55.0,53.0,50.0,86.0,72.0,58.0,...,10.0,10.0,39.0,22.0,51.0,0,3.0,NaN,270.0,94107
20,2013-09-18,78.0,66.0,54.0,55.0,49.0,47.0,78.0,60.0,41.0,...,10.0,10.0,25.0,10.0,30.0,0,1.0,NaN,278.0,94107
21,2013-09-19,80.0,67.0,54.0,56.0,50.0,46.0,77.0,58.0,38.0,...,10.0,10.0,26.0,10.0,33.0,0,0.0,NaN,297.0,94107
22,2013-09-20,73.0,65.0,56.0,59.0,56.0,50.0,87.0,70.0,53.0,...,10.0,9.0,17.0,10.0,23.0,0,6.0,NaN,248.0,94107
23,2013-09-21,68.0,63.0,58.0,59.0,56.0,53.0,90.0,75.0,59.0,...,9.0,2.0,24.0,12.0,28.0,0.23,6.0,Rain,218.0,94107
24,2013-09-22,70.0,63.0,55.0,55.0,53.0,49.0,93.0,70.0,47.0,...,10.0,10.0,29.0,10.0,35.0,0,1.0,NaN,292.0,94107
25,2013-09-23,78.0,68.0,57.0,58.0,54.0,50.0,78.0,64.0,50.0,...,10.0,10.0,24.0,9.0,30.0,0,0.0,NaN,294.0,94107
26,2013-09-24,71.0,65.0,58.0,54.0,52.0,50.0,78.0,66.0,53.0,...,10.0,10.0,36.0,19.0,43.0,0,1.0,NaN,277.0,94107
27,2013-09-25,67.0,62.0,56.0,51.0,47.0,45.0,83.0,64.0,45.0,...,10.0,10.0,35.0,20.0,45.0,0,1.0,NaN,281.0,94107
28,2013-09-26,71.0,62.0,53.0,46.0,43.0,38.0,72.0,53.0,33.0,...,10.0,10.0,24.0,11.0,29.0,0,0.0,NaN,281.0,94107
29,2013-09-27,78.0,66.0,54.0,47.0,41.0,34.0,67.0,46.0,25.0,...,10.0,10.0,23.0,7.0,28.0,0,0.0,NaN,279.0,94107
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2175,2015-08-02,73.0,68.0,63.0,57.0,56.0,55.0,84.0,71.0,57.0,...,10.0,8.0,20.0,12.0,23.0,0,6.0,NaN,265.0,94107
2176,2015-08-03,75.0,70.0,64.0,57.0,54.0,53.0,78.0,64.0,49.0,...,10.0,10.0,22.0,14.0,25.0,0,5.0,NaN,267.0,94107
2177,2015-08-04,75.0,69.0,62.0,57.0,54.0,52.0,78.0,62.0,46.0,...,10.0,10.0,18.0,10.0,22.0,0,5.0,NaN,269.0,94107
2178,2015-08-05,77.0,67.0,57.0,59.0,56.0,54.0,84.0,69.0,54.0,...,10.0,10.0,20.0,8.0,22.0,0,3.0,NaN,278.0,94107
2179,2015-08-06,72.0,65.0,58.0,58.0,57.0,54.0,93.0,77.0,61.0,...,10.0,7.0,21.0,8.0,24.0,T,5.0,Rain-Thunderstorm,309.0,94107
2180,2015-08-07,77.0,69.0,61.0,57.0,56.0,54.0,84.0,69.0,53.0,...,10.0,10.0,22.0,10.0,24.0,0,4.0,NaN,271.0,94107
2181,2015-08-08,70.0,66.0,62.0,57.0,56.0,55.0,84.0,73.0,61.0,...,10.0,10.0,18.0,11.0,25.0,0,6.0,NaN,261.0,94107
2182,2015-08-09,72.0,66.0,59.0,59.0,57.0,55.0,90.0,76.0,61.0,...,10.0,10.0,21.0,11.0,28.0,0,6.0,NaN,251.0,94107
2183,2015-08-10,73.0,67.0,60.0,60.0,57.0,54.0,84.0,73.0,61.0,...,10.0,10.0,22.0,13.0,25.0,0,6.0,NaN,262.0,94107
2184,2015-08-11,73.0,67.0,61.0,58.0,56.0,55.0,84.0,69.0,53.0,...,10.0,10.0,21.0,11.0,24.0,0,5.0,NaN,258.0,94107
2185,2015-08-12,78.0,67.0,55.0,61.0,57.0,50.0,93.0,67.0,41.0,...,10.0,10.0,18.0,9.0,22.0,0,2.0,NaN,285.0,94107
2186,2015-08-13,76.0,70.0,64.0,61.0,59.0,56.0,87.0,70.0,53.0,...,10.0,10.0,20.0,10.0,24.0,0,4.0,NaN,278.0,94107
2187,2015-08-14,76.0,69.0,61.0,60.0,58.0,57.0,87.0,71.0,54.0,...,10.0,10.0,17.0,9.0,21.0,0,4.0,NaN,264.0,94107
2188,2015-08-15,92.0,75.0,57.0,61.0,56.0,50.0,86.0,56.0,26.0,...,8.0,2.0,15.0,5.0,21.0,0,3.0,NaN,306.0,94107
2189,2015-08-16,93.0,77.0,61.0,61.0,57.0,47.0,84.0,56.0,27.0,...,7.0,4.0,16.0,5.0,20.0,0,5.0,NaN,297.0,94107
2190,2015-08-17,80.0,70.0,59.0,60.0,58.0,56.0,90.0,69.0,48.0,...,7.0,6.0,21.0,10.0,24.0,0,1.0,NaN,308.0,94107
2191,2015-08-18,75.0,68.0,61.0,58.0,57.0,55.0,90.0,72.0,54.0,...,8.0,4.0,18.0,10.0,22.0,0,4.0,NaN,310.0,94107
2192,2015-08-19,74.0,69.0,63.0,57.0,56.0,54.0,78.0,66.0,53.0,...,9.0,7.0,20.0,11.0,23.0,0,6.0,NaN,273.0,94107
2193,2015-08-20,70.0,66.0,62.0,57.0,55.0,53.0,84.0,71.0,57.0,...,10.0,10.0,20.0,12.0,24.0,0,6.0,NaN,270.0,94107
2194,2015-08-21,69.0,66.0,62.0,57.0,56.0,55.0,78.0,70.0,61.0,...,10.0,10.0,21.0,11.0,23.0,0,6.0,NaN,262.0,94107
2195,2015-08-22,75.0,68.0,61.0,58.0,56.0,55.0,78.0,66.0,53.0,...,10.0,10.0,22.0,8.0,25.0,0,5.0,NaN,257.0,94107
2196,2015-08-23,73.0,67.0,61.0,56.0,55.0,54.0,78.0,68.0,57.0,...,10.0,10.0,17.0,10.0,21.0,0,7.0,NaN,277.0,94107
2197,2015-08-24,75.0,68.0,61.0,57.0,55.0,54.0,84.0,69.0,53.0,...,10.0,7.0,17.0,10.0,22.0,0,4.0,NaN,281.0,94107
2198,2015-08-25,74.0,67.0,60.0,57.0,56.0,54.0,84.0,69.0,53.0,...,9.0,6.0,18.0,10.0,23.0,0,4.0,NaN,290.0,94107
2199,2015-08-26,79.0,69.0,58.0,58.0,56.0,52.0,87.0,65.0,43.0,...,9.0,6.0,16.0,6.0,21.0,0,4.0,NaN,296.0,94107
2200,2015-08-27,84.0,72.0,59.0,58.0,55.0,46.0,84.0,57.0,30.0,...,10.0,10.0,17.0,6.0,29.0,0,2.0,NaN,272.0,94107
2201,2015-08-28,91.0,77.0,62.0,62.0,58.0,53.0,87.0,60.0,32.0,...,10.0,10.0,24.0,8.0,28.0,0,4.0,NaN,291.0,94107
2202,2015-08-29,76.0,71.0,65.0,66.0,62.0,57.0,87.0,73.0,58.0,...,9.0,3.0,21.0,11.0,25.0,T,6.0,Rain,260.0,94107
2203,2015-08-30,78.0,70.0,61.0,60.0,59.0,56.0,87.0,69.0,50.0,...,10.0,10.0,20.0,11.0,22.0,0,3.0,NaN,276.0,94107
2204,2015-08-31,78.0,69.0,60.0,58.0,57.0,54.0,84.0,67.0,50.0,...,10.0,9.0,18.0,9.0,21.0,0,1.0,NaN,246.0,94107

In [21]:
weather.events.unique()

array([nan, 'Fog', 'Rain', 'Fog-Rain', 'rain', 'Rain-Thunderstorm'], dtype=object)

In [22]:
weather.loc[weather.events == 'rain', 'events'] = "Rain"
weather.loc[weather.events.isnull(), 'events'] = "Normal"

In [23]:
weather.events

0                  Normal
1                  Normal
2                  Normal
3                  Normal
4                  Normal
5                  Normal
6                  Normal
7                  Normal
8                  Normal
9                  Normal
10                 Normal
11                 Normal
12                 Normal
13                 Normal
14                    Fog
15                 Normal
16                 Normal
17                 Normal
18                 Normal
19                 Normal
20                 Normal
21                 Normal
22                 Normal
23                   Rain
24                 Normal
25                 Normal
26                 Normal
27                 Normal
28                 Normal
29                 Normal
              ...
2175               Normal
2176               Normal
2177               Normal
2178               Normal
2179    Rain-Thunderstorm
2180               Normal
2181               Normal
2182               Normal
2183               Normal
2184               Normal
2185               Normal
2186               Normal
2187               Normal
2188               Normal
2189               Normal
2190               Normal
2191               Normal
2192               Normal
2193               Normal
2194               Normal
2195               Normal
2196               Normal
2197               Normal
2198               Normal
2199               Normal
2200               Normal
2201               Normal
2202                 Rain
2203               Normal
2204               Normal
Name: events, dtype: object

In [24]:
weather

,date,max_temperature_f,mean_temperature_f,min_temperature_f,max_dew_point_f,mean_dew_point_f,min_dew_point_f,max_humidity,mean_humidity,min_humidity,...,mean_visibility_miles,min_visibility_miles,max_wind_Speed_mph,mean_wind_speed_mph,max_gust_speed_mph,precipitation_inches,cloud_cover,events,wind_dir_degrees,zip_code
0,2013-08-29,74.0,68.0,61.0,61.0,58.0,56.0,93.0,75.0,57.0,...,10.0,10.0,23.0,11.0,28.0,0,4.0,Normal,286.0,94107
1,2013-08-30,78.0,69.0,60.0,61.0,58.0,56.0,90.0,70.0,50.0,...,10.0,7.0,29.0,13.0,35.0,0,2.0,Normal,291.0,94107
2,2013-08-31,71.0,64.0,57.0,57.0,56.0,54.0,93.0,75.0,57.0,...,10.0,10.0,26.0,15.0,31.0,0,4.0,Normal,284.0,94107
3,2013-09-01,74.0,66.0,58.0,60.0,56.0,53.0,87.0,68.0,49.0,...,10.0,10.0,25.0,13.0,29.0,0,4.0,Normal,284.0,94107
4,2013-09-02,75.0,69.0,62.0,61.0,60.0,58.0,93.0,77.0,61.0,...,10.0,6.0,23.0,12.0,30.0,0,6.0,Normal,277.0,94107
5,2013-09-03,73.0,67.0,60.0,59.0,56.0,51.0,84.0,65.0,46.0,...,10.0,10.0,24.0,15.0,31.0,0,2.0,Normal,276.0,94107
6,2013-09-04,74.0,68.0,61.0,59.0,57.0,56.0,90.0,72.0,53.0,...,10.0,10.0,29.0,19.0,35.0,0,4.0,Normal,269.0,94107
7,2013-09-05,72.0,66.0,60.0,57.0,56.0,54.0,90.0,74.0,57.0,...,10.0,10.0,31.0,21.0,37.0,0,3.0,Normal,270.0,94107
8,2013-09-06,85.0,71.0,56.0,57.0,51.0,45.0,86.0,58.0,29.0,...,10.0,10.0,24.0,8.0,28.0,0,0.0,Normal,287.0,94107
9,2013-09-07,88.0,73.0,58.0,64.0,54.0,46.0,86.0,59.0,31.0,...,10.0,10.0,21.0,8.0,25.0,0,1.0,Normal,305.0,94107
10,2013-09-08,74.0,65.0,56.0,58.0,54.0,52.0,86.0,70.0,53.0,...,10.0,10.0,26.0,11.0,31.0,0,2.0,Normal,299.0,94107
11,2013-09-09,76.0,66.0,55.0,58.0,55.0,52.0,90.0,70.0,50.0,...,10.0,10.0,26.0,11.0,30.0,0,1.0,Normal,303.0,94107
12,2013-09-10,74.0,66.0,57.0,59.0,56.0,54.0,93.0,73.0,53.0,...,10.0,10.0,17.0,8.0,21.0,0,1.0,Normal,230.0,94107
13,2013-09-11,74.0,68.0,62.0,57.0,55.0,54.0,78.0,68.0,57.0,...,10.0,10.0,18.0,9.0,23.0,0,5.0,Normal,219.0,94107
14,2013-09-12,71.0,65.0,59.0,58.0,57.0,55.0,84.0,73.0,61.0,...,10.0,9.0,25.0,11.0,30.0,0,7.0,Fog,268.0,94107
15,2013-09-13,66.0,62.0,57.0,55.0,54.0,54.0,93.0,80.0,67.0,...,10.0,7.0,30.0,15.0,37.0,0,6.0,Normal,271.0,94107
16,2013-09-14,66.0,62.0,57.0,55.0,54.0,53.0,87.0,77.0,67.0,...,10.0,9.0,25.0,16.0,33.0,0,7.0,Normal,265.0,94107
17,2013-09-15,73.0,66.0,58.0,59.0,55.0,52.0,90.0,72.0,53.0,...,10.0,6.0,23.0,13.0,26.0,0,5.0,Normal,276.0,94107
18,2013-09-16,71.0,65.0,59.0,58.0,55.0,53.0,90.0,74.0,57.0,...,10.0,6.0,31.0,16.0,39.0,0,3.0,Normal,274.0,94107
19,2013-09-17,68.0,63.0,57.0,55.0,53.0,50.0,86.0,72.0,58.0,...,10.0,10.0,39.0,22.0,51.0,0,3.0,Normal,270.0,94107
20,2013-09-18,78.0,66.0,54.0,55.0,49.0,47.0,78.0,60.0,41.0,...,10.0,10.0,25.0,10.0,30.0,0,1.0,Normal,278.0,94107
21,2013-09-19,80.0,67.0,54.0,56.0,50.0,46.0,77.0,58.0,38.0,...,10.0,10.0,26.0,10.0,33.0,0,0.0,Normal,297.0,94107
22,2013-09-20,73.0,65.0,56.0,59.0,56.0,50.0,87.0,70.0,53.0,...,10.0,9.0,17.0,10.0,23.0,0,6.0,Normal,248.0,94107
23,2013-09-21,68.0,63.0,58.0,59.0,56.0,53.0,90.0,75.0,59.0,...,9.0,2.0,24.0,12.0,28.0,0.23,6.0,Rain,218.0,94107
24,2013-09-22,70.0,63.0,55.0,55.0,53.0,49.0,93.0,70.0,47.0,...,10.0,10.0,29.0,10.0,35.0,0,1.0,Normal,292.0,94107
25,2013-09-23,78.0,68.0,57.0,58.0,54.0,50.0,78.0,64.0,50.0,...,10.0,10.0,24.0,9.0,30.0,0,0.0,Normal,294.0,94107
26,2013-09-24,71.0,65.0,58.0,54.0,52.0,50.0,78.0,66.0,53.0,...,10.0,10.0,36.0,19.0,43.0,0,1.0,Normal,277.0,94107
27,2013-09-25,67.0,62.0,56.0,51.0,47.0,45.0,83.0,64.0,45.0,...,10.0,10.0,35.0,20.0,45.0,0,1.0,Normal,281.0,94107
28,2013-09-26,71.0,62.0,53.0,46.0,43.0,38.0,72.0,53.0,33.0,...,10.0,10.0,24.0,11.0,29.0,0,0.0,Normal,281.0,94107
29,2013-09-27,78.0,66.0,54.0,47.0,41.0,34.0,67.0,46.0,25.0,...,10.0,10.0,23.0,7.0,28.0,0,0.0,Normal,279.0,94107
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2175,2015-08-02,73.0,68.0,63.0,57.0,56.0,55.0,84.0,71.0,57.0,...,10.0,8.0,20.0,12.0,23.0,0,6.0,Normal,265.0,94107
2176,2015-08-03,75.0,70.0,64.0,57.0,54.0,53.0,78.0,64.0,49.0,...,10.0,10.0,22.0,14.0,25.0,0,5.0,Normal,267.0,94107
2177,2015-08-04,75.0,69.0,62.0,57.0,54.0,52.0,78.0,62.0,46.0,...,10.0,10.0,18.0,10.0,22.0,0,5.0,Normal,269.0,94107
2178,2015-08-05,77.0,67.0,57.0,59.0,56.0,54.0,84.0,69.0,54.0,...,10.0,10.0,20.0,8.0,22.0,0,3.0,Normal,278.0,94107
2179,2015-08-06,72.0,65.0,58.0,58.0,57.0,54.0,93.0,77.0,61.0,...,10.0,7.0,21.0,8.0,24.0,T,5.0,Rain-Thunderstorm,309.0,94107
2180,2015-08-07,77.0,69.0,61.0,57.0,56.0,54.0,84.0,69.0,53.0,...,10.0,10.0,22.0,10.0,24.0,0,4.0,Normal,271.0,94107
2181,2015-08-08,70.0,66.0,62.0,57.0,56.0,55.0,84.0,73.0,61.0,...,10.0,10.0,18.0,11.0,25.0,0,6.0,Normal,261.0,94107
2182,2015-08-09,72.0,66.0,59.0,59.0,57.0,55.0,90.0,76.0,61.0,...,10.0,10.0,21.0,11.0,28.0,0,6.0,Normal,251.0,94107
2183,2015-08-10,73.0,67.0,60.0,60.0,57.0,54.0,84.0,73.0,61.0,...,10.0,10.0,22.0,13.0,25.0,0,6.0,Normal,262.0,94107
2184,2015-08-11,73.0,67.0,61.0,58.0,56.0,55.0,84.0,69.0,53.0,...,10.0,10.0,21.0,11.0,24.0,0,5.0,Normal,258.0,94107
2185,2015-08-12,78.0,67.0,55.0,61.0,57.0,50.0,93.0,67.0,41.0,...,10.0,10.0,18.0,9.0,22.0,0,2.0,Normal,285.0,94107
2186,2015-08-13,76.0,70.0,64.0,61.0,59.0,56.0,87.0,70.0,53.0,...,10.0,10.0,20.0,10.0,24.0,0,4.0,Normal,278.0,94107
2187,2015-08-14,76.0,69.0,61.0,60.0,58.0,57.0,87.0,71.0,54.0,...,10.0,10.0,17.0,9.0,21.0,0,4.0,Normal,264.0,94107
2188,2015-08-15,92.0,75.0,57.0,61.0,56.0,50.0,86.0,56.0,26.0,...,8.0,2.0,15.0,5.0,21.0,0,3.0,Normal,306.0,94107
2189,2015-08-16,93.0,77.0,61.0,61.0,57.0,47.0,84.0,56.0,27.0,...,7.0,4.0,16.0,5.0,20.0,0,5.0,Normal,297.0,94107
2190,2015-08-17,80.0,70.0,59.0,60.0,58.0,56.0,90.0,69.0,48.0,...,7.0,6.0,21.0,10.0,24.0,0,1.0,Normal,308.0,94107
2191,2015-08-18,75.0,68.0,61.0,58.0,57.0,55.0,90.0,72.0,54.0,...,8.0,4.0,18.0,10.0,22.0,0,4.0,Normal,310.0,94107
2192,2015-08-19,74.0,69.0,63.0,57.0,56.0,54.0,78.0,66.0,53.0,...,9.0,7.0,20.0,11.0,23.0,0,6.0,Normal,273.0,94107
2193,2015-08-20,70.0,66.0,62.0,57.0,55.0,53.0,84.0,71.0,57.0,...,10.0,10.0,20.0,12.0,24.0,0,6.0,Normal,270.0,94107
2194,2015-08-21,69.0,66.0,62.0,57.0,56.0,55.0,78.0,70.0,61.0,...,10.0,10.0,21.0,11.0,23.0,0,6.0,Normal,262.0,94107
2195,2015-08-22,75.0,68.0,61.0,58.0,56.0,55.0,78.0,66.0,53.0,...,10.0,10.0,22.0,8.0,25.0,0,5.0,Normal,257.0,94107
2196,2015-08-23,73.0,67.0,61.0,56.0,55.0,54.0,78.0,68.0,57.0,...,10.0,10.0,17.0,10.0,21.0,0,7.0,Normal,277.0,94107
2197,2015-08-24,75.0,68.0,61.0,57.0,55.0,54.0,84.0,69.0,53.0,...,10.0,7.0,17.0,10.0,22.0,0,4.0,Normal,281.0,94107
2198,2015-08-25,74.0,67.0,60.0,57.0,56.0,54.0,84.0,69.0,53.0,...,9.0,6.0,18.0,10.0,23.0,0,4.0,Normal,290.0,94107
2199,2015-08-26,79.0,69.0,58.0,58.0,56.0,52.0,87.0,65.0,43.0,...,9.0,6.0,16.0,6.0,21.0,0,4.0,Normal,296.0,94107
2200,2015-08-27,84.0,72.0,59.0,58.0,55.0,46.0,84.0,57.0,30.0,...,10.0,10.0,17.0,6.0,29.0,0,2.0,Normal,272.0,94107
2201,2015-08-28,91.0,77.0,62.0,62.0,58.0,53.0,87.0,60.0,32.0,...,10.0,10.0,24.0,8.0,28.0,0,4.0,Normal,291.0,94107
2202,2015-08-29,76.0,71.0,65.0,66.0,62.0,57.0,87.0,73.0,58.0,...,9.0,3.0,21.0,11.0,25.0,T,6.0,Rain,260.0,94107
2203,2015-08-30,78.0,70.0,61.0,60.0,59.0,56.0,87.0,69.0,50.0,...,10.0,10.0,20.0,11.0,22.0,0,3.0,Normal,276.0,94107
2204,2015-08-31,78.0,69.0,60.0,58.0,57.0,54.0,84.0,67.0,50.0,...,10.0,9.0,18.0,9.0,21.0,0,1.0,Normal,246.0,94107

In [25]:
events = pd.get_dummies(weather.events)

In [26]:
events

      Fog  Fog-Rain  Normal  Rain  Rain-Thunderstorm
0       0         0       1     0                  0
1       0         0       1     0                  0
2       0         0       1     0                  0
3       0         0       1     0                  0
4       0         0       1     0                  0
5       0         0       1     0                  0
6       0         0       1     0                  0
7       0         0       1     0                  0
8       0         0       1     0                  0
9       0         0       1     0                  0
10      0         0       1     0                  0
11      0         0       1     0                  0
12      0         0       1     0                  0
13      0         0       1     0                  0
14      1         0       0     0                  0
15      0         0       1     0                  0
16      0         0       1     0                  0
17      0         0       1     0                  0
18      0         0       1     0                  0
19      0         0       1     0                  0
20      0         0       1     0                  0
21      0         0       1     0                  0
22      0         0       1     0                  0
23      0         0       0     1                  0
24      0         0       1     0                  0
25      0         0       1     0                  0
26      0         0       1     0                  0
27      0         0       1     0                  0
28      0         0       1     0                  0
29      0         0       1     0                  0
...   ...       ...     ...   ...                ...
2175    0         0       1     0                  0
2176    0         0       1     0                  0
2177    0         0       1     0                  0
2178    0         0       1     0                  0
2179    0         0       0     0                  1
2180    0         0       1     0                  0
2181    0         0       1     0                  0
2182    0         0       1     0                  0
2183    0         0       1     0                  0
2184    0         0       1     0                  0
2185    0         0       1     0                  0
2186    0         0       1     0                  0
2187    0         0       1     0                  0
2188    0         0       1     0                  0
2189    0         0       1     0                  0
2190    0         0       1     0                  0
2191    0         0       1     0                  0
2192    0         0       1     0                  0
2193    0         0       1     0                  0
2194    0         0       1     0                  0
2195    0         0       1     0                  0
2196    0         0       1     0                  0
2197    0         0       1     0                  0
2198    0         0       1     0                  0
2199    0         0       1     0                  0
2200    0         0       1     0                  0
2201    0         0       1     0                  0
2202    0         0       0     1                  0
2203    0         0       1     0                  0
2204    0         0       1     0                  0

[733 rows x 5 columns]

In [27]:
weather = weather.merge(events, left_index = True, right_index = True)
weather = weather.drop(['events','zip_code'],1)

In [31]:
weather.isnull().sum()

date                               0
max_temperature_f                  0
mean_temperature_f                 0
min_temperature_f                  0
max_dew_point_f                    0
mean_dew_point_f                   0
min_dew_point_f                    0
max_humidity                       0
mean_humidity                      0
min_humidity                       0
max_sea_level_pressure_inches      0
mean_sea_level_pressure_inches     0
min_sea_level_pressure_inches      0
max_visibility_miles               0
mean_visibility_miles              0
min_visibility_miles               0
max_wind_Speed_mph                 0
mean_wind_speed_mph                0
max_gust_speed_mph                13
precipitation_inches               0
cloud_cover                        0
wind_dir_degrees                   0
Fog                                0
Fog-Rain                           0
Normal                             0
Rain                               0
Rain-Thunderstorm                  0
dtype: int64

In [32]:
weather = weather.drop(['max_gust_speed_mph'],1)

In [33]:
weather.isnull().sum()

date                              0
max_temperature_f                 0
mean_temperature_f                0
min_temperature_f                 0
max_dew_point_f                   0
mean_dew_point_f                  0
min_dew_point_f                   0
max_humidity                      0
mean_humidity                     0
min_humidity                      0
max_sea_level_pressure_inches     0
mean_sea_level_pressure_inches    0
min_sea_level_pressure_inches     0
max_visibility_miles              0
mean_visibility_miles             0
min_visibility_miles              0
max_wind_Speed_mph                0
mean_wind_speed_mph               0
precipitation_inches              0
cloud_cover                       0
wind_dir_degrees                  0
Fog                               0
Fog-Rain                          0
Normal                            0
Rain                              0
Rain-Thunderstorm                 0
dtype: int64

In [34]:
weather.precipitation_inches = pd.to_numeric(weather.precipitation_inches, errors = 'coerce')
weather.loc[weather.precipitation_inches.isnull(), 
            'precipitation_inches'] = weather[weather.precipitation_inches.notnull()].precipitation_inches.median()

In [35]:
train = train.merge(weather, on = train.date)

In [37]:
train['date'] = train['date_x']
train.drop(['date_y','date_x'],1, inplace= True)
train.head()

,trips,max_temperature_f,mean_temperature_f,min_temperature_f,max_dew_point_f,mean_dew_point_f,min_dew_point_f,max_humidity,mean_humidity,min_humidity,...,mean_wind_speed_mph,precipitation_inches,cloud_cover,wind_dir_degrees,Fog,Fog-Rain,Normal,Rain,Rain-Thunderstorm,date
0,742,74.0,68.0,61.0,61.0,58.0,56.0,93.0,75.0,57.0,...,11.0,0.0,4.0,286.0,0,0,1,0,0,2013-08-29
1,699,78.0,69.0,60.0,61.0,58.0,56.0,90.0,70.0,50.0,...,13.0,0.0,2.0,291.0,0,0,1,0,0,2013-08-30
2,628,71.0,64.0,57.0,57.0,56.0,54.0,93.0,75.0,57.0,...,15.0,0.0,4.0,284.0,0,0,1,0,0,2013-08-31
3,683,74.0,66.0,58.0,60.0,56.0,53.0,87.0,68.0,49.0,...,13.0,0.0,4.0,284.0,0,0,1,0,0,2013-09-01
4,652,75.0,69.0,62.0,61.0,60.0,58.0,93.0,77.0,61.0,...,12.0,0.0,6.0,277.0,0,0,1,0,0,2013-09-02

In [39]:
stations.installation_date = pd.to_datetime(stations.installation_date, format = "%m/%d/%Y").dt.date
stations.head()

,id,lat,long,dock_count,name,installation_date
0,2,37.329732,-121.901782,27,San Jose Diridon Caltrain Station,2013-08-06
1,3,37.330698,-121.888979,15,San Jose Civic Center,2013-08-05
2,4,37.333988,-121.894902,11,Santa Clara at Almaden,2013-08-06
3,5,37.331415,-121.893200,19,Adobe on Almaden,2013-08-05
4,6,37.336721,-121.894074,15,San Pedro Square,2013-08-07

In [40]:
total_docks = []
for day in train.date:
    total_docks.append(sum(stations[stations.installation_date <= day].dock_count))
total_docks

[1150,
 1150,
 1150,
 1150,
 1150,
 1150,
 1150,
 1150,
 1150,
 1150,
 1150,
 1150,
 1150,
 1150,
 1150,
 1150,
 1150,
 1150,
 1150,
 1150,
 1150,
 1150,
 1150,
 1150,
 1150,
 1150,
 1150,
 1150,
 1150,
 1150,
 1150,
 1150,
 1150,
 1150,
 1150,
 1150,
 1150,
 1150,
 1150,
 1150,
 1150,
 1150,
 1150,
 1150,
 1150,
 1150,
 1150,
 1150,
 1150,
 1150,
 1150,
 1150,
 1150,
 1150,
 1150,
 1150,
 1150,
 1150,
 1150,
 1150,
 1150,
 1150,
 1150,
 1150,
 1150,
 1150,
 1150,
 1150,
 1150,
 1150,
 1150,
 1150,
 1150,
 1150,
 1150,
 1150,
 1150,
 1150,
 1150,
 1150,
 1150,
 1150,
 1150,
 1150,
 1150,
 1150,
 1150,
 1150,
 1150,
 1150,
 1150,
 1150,
 1150,
 1150,
 1150,
 1150,
 1150,
 1150,
 1150,
 1150,
 1150,
 1150,
 1150,
 1150,
 1150,
 1150,
 1150,
 1150,
 1150,
 1150,
 1150,
 1150,
 1150,
 1150,
 1150,
 1150,
 1150,
 1150,
 1150,
 1150,
 1150,
 1150,
 1150,
 1150,
 1191,
 1191,
 1191,
 1191,
 1191,
 1191,
 1191,
 1191,
 1191,
 1191,
 1191,
 1191,
 1191,
 1191,
 1191,
 1191,
 1191,
 1191,
 1191,
 1191,
 1191,
 1191,
 1206,
 1206,
 1206,
 1206,
 1206,
 1206,
 1206,
 1206,
 1206,
 1206,
 1206,
 1206,
 1206,
 1206,
 1206,
 1206,
 1206,
 1206,
 1206,
 1206,
 1206,
 1206,
 1206,
 1206,
 1206,
 1206,
 1206,
 1206,
 1206,
 1221,
 1221,
 1221,
 1221,
 1221,
 1221,
 1221,
 1221,
 1221,
 1221,
 1221,
 1221,
 1221,
 1221,
 1221,
 1221,
 1221,
 1221,
 1221,
 1221,
 1221,
 1221,
 1221,
 1221,
 1221,
 1221,
 1221,
 1221,
 1221,
 1221,
 1221,
 1221,
 1221,
 1221,
 1221,
 1221,
 1221,
 1221,
 1221,
 1221,
 1221,
 1221,
 1221,
 1221,
 1221,
 1221,
 1221,
 1221,
 1236,
 1236,
 1236,
 1236,
 1236,
 1236,
 1236,
 1236,
 1236,
 1236,
 1236,
 1236,
 1236,
 1236,
 1236,
 1236,
 1236,
 1236,
 1236,
 1236,
 1236,
 1236,
 1236,
 1236,
 1236,
 1236,
 1236,
 1236,
 1236,
 1236,
 1236,
 1236,
 1236,
 1236,
 1236,
 1236,
 1236,
 1236,
 1236,
 1236,
 1236,
 1236,
 1236,
 1236,
 1236,
 1236,
 1236,
 1236,
 1236,
 1236,
 1236,
 1236,
 1236,
 1236,
 1236,
 1236,
 1236,
 1236,
 1236,
 1236,
 1236,
 1236,
 1236,
 1236,
 1236,
 1236,
 1236,
 1236,
 1236,
 1236,
 1236,
 1236,
 1236,
 1236,
 1236,
 1236,
 1236,
 1236,
 1236,
 1236,
 1236,
 1236,
 1236,
 1236,
 1236,
 1236,
 1236,
 1236,
 1236,
 1236,
 1236,
 1236,
 1236,
 1236,
 1236,
 1236,
 1236,
 1236,
 1236,
 1236,
 1236,
 1236,
 1236,
 1236,
 1236,
 1236,
 1236,
 1236,
 1236,
 1236,
 1236,
 1236,
 1236,
 1236,
 1236,
 1236,
 1236,
 1236,
 1236,
 1236,
 1236,
 1236,
 1236,
 1236,
 1236,
 1236,
 1236,
 1236,
 1236,
 1236,
 1236,
 1236,
 1236,
 1236,
 1236,
 1236,
 1236,
 1236,
 1236,
 1236,
 1236,
 1236,
 1236,
 1236,
 1236,
 1236,
 1236,
 1236,
 1236,
 1236,
 1236,
 1236,
 1236,
 1236,
 1236,
 1236,
 1236,
 1236,
 1236,
 1236,
 1236,
 1236,
 1236,
 1236,
 1236,
 1236,
 1236,
 1236,
 1236,
 1236,
 1236,
 1236,
 1236,
 1236,
 1236,
 1236,
 1236,
 1236,
 1236,
 1236,
 1236,
 1236,
 1236,
 1236,
 1236,
 1236,
 1236,
 1236,
 1236,
 1236,
 1236,
 1236,
 1236,
 1236,
 1236,
 1236,
 1236,
 1236,
 1236,
 1236,
 1236,
 1236,
 1236,
 1236,
 1236,
 1236,
 1236,
 1236,
 1236,
 1236,
 1236,
 1236,
 1236,
 1236,
 1236,
 1236,
 1236,
 1236,
 1236,
 1236,
 1236,
 1236,
 1236,
 1236,
 1236,
 1236,
 1236,
 1236,
 1236,
 1236,
 1236,
 1236,
 1236,
 1236,
 1236,
 1236,
 1236,
 1236,
 1236,
 1236,
 1236,
 1236,
 1236,
 1236,
 1236,
 1236,
 1236,
 1236,
 1236,
 1236,
 1236,
 1236,
 1236,
 1236,
 1236,
 1236,
 1236,
 1236,
 1236,
 1236,
 1236,
 1236,
 1236,
 1236,
 1236,
 1236,
 1236,
 1236,
 1236,
 1236,
 1236,
 1236,
 1236,
 1236,
 1236,
 1236,
 1236,
 1236,
 1236,
 1236,
 1236,
 1236,
 1236,
 1236,
 1236,
 1236,
 1236,
 1236,
 1236,
 1236,
 1236,
 1236,
 1236,
 1236,
 1236,
 1236,
 1236,
 1236,
 1236,
 1236,
 1236,
 1236,
 1236,
 1236,
 1236,
 1236,
 1236,
 1236,
 1236,
 1236,
 1236,
 1236,
 1236,
 1236,
 1236,
 1236,
 1236,
 1236,
 1236,
 1236,
 1236,
 1236,
 1236,
 1236,
 1236,
 1236,
 1236,
 1236,
 1236,
 1236,
 1236,
 1236,
 1236,
 1236,
 1236,
 1236,
 1236,
 1236,
 1236,
 1236,
 1236,
 1236,
 1236,
 1236,
 1236,
 1236,
 1236,
 1236,
 1236,
 1236,
 1236,
 1236,
 1236,
 1236,
 1236,
 1236,
 1236,
 1236,
 1236,
 1236,
 1236,
 1236,
 1236,
 1236,
 1236,
 1236,
 1236,
 1236,
 1236,
 1236,
 1236,
 1236,
 1236,
 1236,
 1236,
 1236,
 1236,
 1236,
 1236,
 1236,
 1236,
 1236,
 1236,
 1236,
 1236,
 1236,
 1236,
 1236,
 1236,
 1236,
 1236,
 1236,
 1236,
 1236,
 1236,
 1236,
 1236,
 1236,
 1236,
 1236,
 1236,
 1236,
 1236,
 1236,
 1236,
 1236,
 1236,
 1236,
 1236,
 1236,
 1236,
 1236,
 1236,
 1236,
 1236,
 1236,
 1236,
 1236,
 1236,
 1236,
 1236,
 1236,
 1236,
 1236,
 1236,
 1236,
 1236,
 1236,
 1236,
 1236,
 1236,
 1236,
 1236,
 1236,
 1236,
 1236,
 1236,
 1236,
 1236,
 1236,
 1236,
 1236,
 1236,
 1236,
 1236,
 1236,
 1236,
 1236,
 1236,
 1236,
 1236,
 1236,
 1236,
 1236,
 1236,
 1236,
 1236,
 1236,
 1236,
 1236,
 1236,
 1236,
 1236,
 1236,
 1236,
 1236,
 1236,
 1236,
 1236,
 1236,
 1236,
 1236,
 1236,
 1236,
 1236,
 1236,
 1236,
 1236,
 1236,
 1236,
 1236,
 1236,
 1236,
 1236,
 1236,
 1236,
 1236,
 1236,
 1236,
 1236,
 1236,
 1236,
 1236,
 1236,
 1236,
 1236,
 1236,
 1236,
 1236,
 1236,
 1236,
 1236,
 1236,
 1236,
 1236,
 1236,
 1236,
 1236,
 1236,
 1236]

In [41]:
train['total_docks'] = total_docks

In [42]:
calendar = USFederalHolidayCalendar()
holidays = calendar.holidays(start=train.date.min(), end=train.date.max())
holidays = pd.to_datetime(holidays, format='%Y/%m/%d').date
train['holiday'] = train.date.isin(holidays)

In [44]:
train.holiday = train.holiday.map(lambda x: 1 if x == True else 0)
train.head()

,trips,max_temperature_f,mean_temperature_f,min_temperature_f,max_dew_point_f,mean_dew_point_f,min_dew_point_f,max_humidity,mean_humidity,min_humidity,...,cloud_cover,wind_dir_degrees,Fog,Fog-Rain,Normal,Rain,Rain-Thunderstorm,date,total_docks,holiday
0,742,74.0,68.0,61.0,61.0,58.0,56.0,93.0,75.0,57.0,...,4.0,286.0,0,0,1,0,0,2013-08-29,1150,0
1,699,78.0,69.0,60.0,61.0,58.0,56.0,90.0,70.0,50.0,...,2.0,291.0,0,0,1,0,0,2013-08-30,1150,0
2,628,71.0,64.0,57.0,57.0,56.0,54.0,93.0,75.0,57.0,...,4.0,284.0,0,0,1,0,0,2013-08-31,1150,0
3,683,74.0,66.0,58.0,60.0,56.0,53.0,87.0,68.0,49.0,...,4.0,284.0,0,0,1,0,0,2013-09-01,1150,0
4,652,75.0,69.0,62.0,61.0,60.0,58.0,93.0,77.0,61.0,...,6.0,277.0,0,0,1,0,0,2013-09-02,1150,1

In [45]:
train['year'] = pd.to_datetime(train['date']).dt.year
train['month'] = pd.to_datetime(train['date']).dt.month
train['weekday'] = pd.to_datetime(train['date']).dt.weekday
labels = train.trips
train = train.drop(['trips', 'date'], 1)

In [46]:
labels

0       742
1       699
2       628
3       683
4       652
5       592
6       599
7       671
8       810
9       788
10      692
11      765
12      892
13      876
14      933
15      969
16      690
17      613
18      912
19     1066
20     1106
21     1044
22     1101
23      384
24      567
25     1044
26     1070
27     1260
28     1079
29     1095
       ...
703     317
704    1278
705    1356
706    1334
707    1296
708    1192
709     427
710     357
711    1280
712    1395
713    1396
714    1399
715    1178
716     445
717     392
718    1418
719    1405
720    1345
721    1351
722    1211
723     417
724     308
725    1300
726    1418
727    1464
728    1439
729    1219
730     341
731     326
732    1367
Name: trips, dtype: int64

In [47]:
X_train, X_test, y_train, y_test = train_test_split(train, labels, test_size=0.2, random_state = 2)

In [48]:
def scoring(clf):
    scores = cross_val_score(clf, X_train, y_train, cv=15, n_jobs=1, scoring = 'neg_median_absolute_error')
    print np.median(scores) * -1

In [49]:
rfr = RandomForestRegressor(n_estimators = 55,
                            min_samples_leaf = 3,
                            random_state = 2)
scoring(rfr)

54.5269230265

In [52]:
gbr = GradientBoostingRegressor(learning_rate = 0.12,
                                n_estimators = 150,
                                max_depth = 8,
                                min_samples_leaf = 1,
                                random_state = 2)
scoring(gbr)

54.4664966981

In [53]:
dtr = DecisionTreeRegressor(min_samples_leaf = 3,
                            max_depth = 8,
                            random_state = 2)
scoring(dtr)

In [55]:
rfr = rfr.fit(X_train, y_train)
gbr = gbr.fit(X_train, y_train)
dtr = dtr.fit(X_train, y_train)

rfr_preds = rfr.predict(X_test)
gbr_preds = gbr.predict(X_test)
dtr_preds = dtr.predict(X_test)
final_preds = rfr_preds*0.5 + gbr_preds*0.5 + dtr_preds*0
print "Daily error of trip count:", median_absolute_error(y_test, final_preds)

Daily error of trip count: 57.130215764